### ISSUE TITLE
TypeError: no implicit conversion of Sprockets::BundledAsset into String Compass#1836

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass-rails#186]
compass/compass#1836

**Comment by craigmcnamara** [comment]
Try with the latest master. If the problem persists please re-open this ticket with more information.

**Comment by jhk753** [comment]
Hi, 

I having the exact same issue here. But I don't want to disable image_optim because I want it to compress my images and sprites.
So everything is working great till it get to the spreadsheets.
Then here it goes:

```
TypeError: no implicit conversion of Sprockets::BundledAsset into String
  (in /Users/julien/juliedesk/app/assets/stylesheets/admin.css.scss)
/Users/julien/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/image_size.rb:19:in `extname'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/image_size.rb:19:in `initialize'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/image_size.rb:54:in `new'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/image_size.rb:54:in `image_dimensions'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/image_size.rb:12:in `image_height'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/script/tree/funcall.rb:140:in `_perform'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/script/tree/node.rb:50:in `perform'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:394:in `visit_prop'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `block in with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:363:in `block (4 levels) in visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:363:in `map'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:363:in `block (3 levels) in visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:363:in `block (2 levels) in visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:84:in `perform_arguments'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:358:in `block in visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:98:in `block in with_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:98:in `with_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:346:in `visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `block in with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:363:in `block (4 levels) in visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:363:in `map'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:363:in `block (3 levels) in visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:363:in `block (2 levels) in visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:84:in `perform_arguments'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:358:in `block in visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:98:in `block in with_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:98:in `with_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:346:in `visit_mixin'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `block in with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `map'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `block in with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `map'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `block in with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `map'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `block in with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:325:in `map'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:88:in `block in with_import'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:88:in `with_import'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `block in with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:115:in `with_frame'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/stack.rb:79:in `with_base'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:52:in `map'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:157:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/visitors/perform.rb:8:in `visit'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/root_node.rb:36:in `css_tree'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/tree/root_node.rb:20:in `render'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sass-3.4.10/lib/sass/engine.rb:268:in `render'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/compass-rails-2.0.4/lib/compass-rails/patches/sass_importer.rb:48:in `evaluate'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `build_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `each'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `compile'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/julien/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/julien/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/julien/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```
