### ISSUE TITLE
Sprite imports no longer work

### ISSUE THREAD

**Issue by jaroslawr** [Compass/compass-rails#216]
I have a line in my .scss that says

```
@import "layout/icons/icons-nc/*.png";
```

The path exists and is resolvable, as proved by the fact that replacing it by:

```
@import "layout/icons/icons-nc/xyz.png";
```

works just fine. With the wildcard however, on compass-rails 2.0.2 or master, I get an error:

```
couldn't find file 'layout/icons/icons-nc/*.png'

sprockets (2.12.3) lib/sprockets/base.rb:153:in `resolve'
sprockets (2.12.3) lib/sprockets/context.rb:108:in `resolve'
sprockets (2.12.3) lib/sprockets/context.rb:119:in `depend_on'
/home/jarek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/compass-rails-23904f25a078/lib/compass-rails/patches/sass_importer.rb:37:in `block in evaluate'
/home/jarek/.rbenv/versions/2.1.5/lib/ruby/2.1.0/set.rb:263:in `each_key'
/home/jarek/.rbenv/versions/2.1.5/lib/ruby/2.1.0/set.rb:263:in `each'
/home/jarek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/compass-rails-23904f25a078/lib/compass-rails/patches/sass_importer.rb:36:in `map'
/home/jarek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/compass-rails-23904f25a078/lib/compass-rails/patches/sass_importer.rb:36:in `evaluate'
```

It seems as if compass-rails causes an attempt to try to resolve it as a single path, where in fact first the wildcard has to be resolved?

**Comment by craigmcnamara** [comment]
Can you try with `gem 'sprockets', '~> 2.13.0'` and let me know if it's still a problem?

**Comment by jaroslawr** [comment]
I am on sprockets 2.12.3. If I try to change the version to ~> 2.13.0, I get just:

```
Could not find gem 'sprockets (~> 2.13.0) ruby' in the gems available on this machine.
```

when doing an bundle update.

**Comment by craigmcnamara** [comment]
Seems like a problem with the sass globbing importer.

**Comment by aaronmcadam** [comment]
I'm having the same issue, it doesn't look like `2.13.0` has been released on rubygems. Is it worth trying `3.0.0.beta.6` or is that a complete rewrite?

**Comment by bguban** [comment]
I have the same problem. Any ideas how to fix it?
This problem began with Rails 4.2.0.

**Comment by McRip** [comment]
I got the same problem since I upgraded to Rails 4.2.

@aaronmcadam Sprockets 3 is not a rewrite but a major release, so additional steps are necessary to upgrade. And I don't know if this fixes this problem.

**Comment by aaronmcadam** [comment]
Ah, thanks for the clarification @McRip. Myself and a colleague looked at this earlier, it seems to be [this changeset](https://github.com/rails/sass-rails/commit/91f7509eb12d3e3f9f9dc564570f8f5dbf3b8c0a) that removes the `context` that compass was trying to pass through. It also seems to try to `@import` the file it's given, so it's trying to find a file called `*.png` and failing.

**Comment by craigmcnamara** [comment]
So, I'm working on adding some better tests that actually assert compass features like sprites are working. Before the tests only asserted that `rake assets:precompile` didn't explode. Would someone on this thread like to take a run at fixing this importer while I get the test suite in shape to prevent new regressions?

**Comment by craigmcnamara** [comment]
You can follow the progress here: https://github.com/Compass/compass-rails/tree/test-sprites

**Comment by craigmcnamara** [comment]
try `gem 'compass-rails', github: 'Compass/compass-rails'` and let me know how it works.

**Comment by jaroslawr** [comment]
Seems to have helped, thank you!

**Comment by McRip** [comment]
This works for me too. Thanks a lot!
Can anybody tell when a bugfix release will be made, that includes this fix?

**Comment by lacco** [comment]
I updated to ```compass-rails``` master to get the fix, and it fixes it locally. When I deploy on Heroku, I get the following error:

```
       I, [2015-01-06T10:30:34.868259 #4257]  INFO -- : Writing /tmp/build_7bb4cae501725a62c29b179d6b3993f3/public/assets/active_admin-4cf6a9e1232d993627c16534fa841f92.css
       Warning. Error encountered while saving cache 8c196ff6ea0b174ed4002078299c0b356620228e/*.pngc: can't dump anonymous class #<Class:0x007ff71c6411d8>
       rake aborted!
       NoMethodError: undefined method `digest_path' for nil:NilClass
       (in /tmp/build_7bb4cae501725a62c29b179d6b3993f3/app/assets/stylesheets/application.css.scss)
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/bundler/gems/compass-rails-38dbd33a3f3c/lib/compass-rails/railties/4_0.rb:29:in `block in <class:Railtie>'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/callbacks.rb:61:in `[]'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/callbacks.rb:61:in `block in run_sprite_saved'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/callbacks.rb:61:in `each'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/callbacks.rb:61:in `run_sprite_saved'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/compass-core-1.0.1/lib/compass/configuration/inheritance.rb:167:in `run_sprite_saved'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/compass-1.0.1/lib/compass/sass_extensions/sprites/sprite_methods.rb:100:in `save!'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/compass-1.0.1/lib/compass/sass_extensions/sprites/sprite_methods.rb:59:in `generate'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/compass-1.0.1/lib/compass/sass_extensions/functions/sprites.rb:179:in `sprite_url'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/script/tree/funcall.rb:140:in `_perform'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/script/tree/node.rb:50:in `perform'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/tree/visitors/perform.rb:384:in `visit_prop'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/tree/visitors/base.rb:36:in `visit'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/stack.rb:79:in `block in with_base'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/stack.rb:115:in `with_frame'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/stack.rb:79:in `with_base'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/tree/visitors/perform.rb:158:in `visit'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/tree/visitors/perform.rb:420:in `block (2 levels) in visit_rule'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/tree/visitors/perform.rb:420:in `map'
       /tmp/build_7bb4cae501725a62c29b179d6b3993f3/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/tree/visitors/perform.rb:420:in `block in visit_rule'
```

Not sure if this directly related to this issue, but the warning in the second line shows some problems with the sprite-wildcard. Or perhaps this issue is related to https://github.com/Compass/compass-rails/issues/158 ?

I am using rails (4.2), sass (3.4.9), sass-rails (5.0.1), compass-rails (38dbd33a3f).
