### ISSUE TITLE
NoMethodError when deploying to heroku with sprite generation

### ISSUE THREAD

**Issue by lacco** [Compass/compass-rails#221]
I updated to Rails 4.2, sass 3.4.9 and compass-rails 2.0.3 (also tried master) a few days ago, and now I get the following error when deploying to heroku:

```
       I, [2015-01-08T10:00:56.475097 #6458]  INFO -- : Writing /tmp/build_58ec712a3079ccdce5d04f610c8377a1/public/assets/active_admin-4cf6a9e1232d993627c16534fa841f92.css
       rake aborted!
       NoMethodError: undefined method `digest_path' for nil:NilClass
       (in /tmp/build_58ec712a3079ccdce5d04f610c8377a1/app/assets/stylesheets/application.css.scss)
       /tmp/build_58ec712a3079ccdce5d04f610c8377a1/vendor/bundle/ruby/2.0.0/bundler/gems/compass-rails-52bd20af8178/lib/compass-rails/railties/4_0.rb:29:in `block in <class:Railtie>'
       /tmp/build_58ec712a3079ccdce5d04f610c8377a1/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/callbacks.rb:61:in `[]'
       /tmp/build_58ec712a3079ccdce5d04f610c8377a1/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/callbacks.rb:61:in `block in run_sprite_saved'
       /tmp/build_58ec712a3079ccdce5d04f610c8377a1/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/callbacks.rb:61:in `each'
       /tmp/build_58ec712a3079ccdce5d04f610c8377a1/vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/callbacks.rb:61:in `run_sprite_saved'
       /tmp/build_58ec712a3079ccdce5d04f610c8377a1/vendor/bundle/ruby/2.0.0/gems/compass-core-1.0.1/lib/compass/configuration/inheritance.rb:167:in `run_sprite_saved'
       /tmp/build_58ec712a3079ccdce5d04f610c8377a1/vendor/bundle/ruby/2.0.0/gems/compass-
```

It seems that this issue is very similar to a previous one that already had been solved for me, https://github.com/Compass/compass-rails/issues/158 . Any idea how to fix this, are there others having similar problems?

**Comment by craigmcnamara** [comment]
Try the latest master. There was a sprite patch that had to be rewritten for Rails 4.2 compatibility.
