### ISSUE TITLE
no implicit conversion of Sprockets::Asset into String

### ISSUE THREAD

**Issue by thaichor** [Compass/compass-rails#256]
Error occurs in development environment. Info are listed below. Errors occurs when use image-height.

compass-rails point to master
compass 1.0.3

```
gem 'compass-rails',                github: 'Compass/compass-rails'
sass-rails (~> 5.0.4)
sprockets (3.5.2)
```

```
compass-rails (3.0.0)
      compass (~> 1.0.0)
      sass-rails (< 5.1)
      sprockets (< 4.0)
```

```
TypeError - no implicit conversion of Sprockets::Asset into String:
  compass-core (1.0.3) lib/compass/core/sass_extensions/functions/image_size.rb:19:in `initialize'
  compass-core (1.0.3) lib/compass/core/sass_extensions/functions/image_size.rb:54:in `image_dimensions'
  compass-core (1.0.3) lib/compass/core/sass_extensions/functions/image_size.rb:12:in `image_height'
  sass (3.4.20) lib/sass/script/tree/funcall.rb:140:in `_perform'
  sass (3.4.20) lib/sass/script/tree/node.rb:50:in `perform'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:395:in `visit_prop'
  sass (3.4.20) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.20) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.20) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.20) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:364:in `block (4 levels) in visit_mixin'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:364:in `block (3 levels) in visit_mixin'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:364:in `block (2 levels) in visit_mixin'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:84:in `perform_arguments'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:359:in `block in visit_mixin'
  sass (3.4.20) lib/sass/stack.rb:98:in `block in with_mixin'
  sass (3.4.20) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.20) lib/sass/stack.rb:98:in `with_mixin'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:347:in `visit_mixin'
  sass (3.4.20) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.20) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.20) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.20) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
  sass (3.4.20) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.20) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.20) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.20) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
  sass (3.4.20) lib/sass/stack.rb:88:in `block in with_import'
  sass (3.4.20) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.20) lib/sass/stack.rb:88:in `with_import'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:323:in `visit_import'
  sass (3.4.20) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.20) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.20) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.20) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.20) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:166:in `visit_children'
  sass (3.4.20) lib/sass/tree/visitors/base.rb:36:in `block in visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:186:in `visit_root'
  sass (3.4.20) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:157:in `visit'
  sass (3.4.20) lib/sass/tree/visitors/perform.rb:8:in `visit'
  sass (3.4.20) lib/sass/tree/root_node.rb:36:in `css_tree'
  sass (3.4.20) lib/sass/tree/root_node.rb:20:in `render'
  sass (3.4.20) lib/sass/engine.rb:278:in `render'
   () Users/thaichorseng/.rvm/gems/ruby-2.1.5@yoolk_website/bundler/gems/compass-rails-a1c890628d61/lib/compass-rails/patches/sass_importer.rb:48:in `evaluate'
  tilt (2.0.1) lib/tilt/template.rb:96:in `render'
  sprockets (3.5.2) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.5.2) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.5.2) lib/sprockets/utils.rb:183:in `dfs'
  sprockets (3.5.2) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.5.2) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.5.2) lib/sprockets/base.rb:73:in `find_all_linked_assets'
  sprockets (3.5.2) lib/sprockets/manifest.rb:142:in `block in find'
  sprockets (3.5.2) lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:225:in `block in stat_tree'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:209:in `block in stat_directory'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:206:in `stat_directory'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:224:in `stat_tree'
  sprockets (3.5.2) lib/sprockets/legacy.rb:105:in `block in logical_paths'
  sprockets (3.5.2) lib/sprockets/legacy.rb:104:in `logical_paths'
  sprockets (3.5.2) lib/sprockets/manifest.rb:140:in `find'
  sprockets-rails (3.0.0) lib/sprockets/railtie.rb:41:in `precompiled_assets'
  sprockets-rails (3.0.0) lib/sprockets/railtie.rb:34:in `asset_precompiled?'
  sprockets-rails (3.0.0) lib/sprockets/railtie.rb:205:in `block (3 levels) in <class:Railtie>'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:346:in `precompiled?'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:350:in `raise_unless_precompiled_asset'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:324:in `digest_path'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:312:in `asset_path'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:90:in `block in resolve_asset_path'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:230:in `block in resolve_asset'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:229:in `resolve_asset'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:89:in `resolve_asset_path'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
  actionview (4.2.5) lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
  actionview (4.2.5) lib/action_view/helpers/asset_url_helper.rb:292:in `image_path'
  app/helpers/application_helper.rb:6:in `retina_tag'
  app/views/home/_header.html.haml:4:in `block in _app_views_home__header_html_haml__963867605498114295_70251249353320'
  haml (4.0.7) lib/haml/helpers.rb:368:in `block in capture_haml'
  haml (4.0.7) lib/haml/helpers.rb:608:in `with_haml_buffer'
  haml (4.0.7) lib/haml/helpers.rb:364:in `capture_haml'
  haml (4.0.7) lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
  actionview (4.2.5) lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:69:in `content_tag_with_haml'
  actionview (4.2.5) lib/action_view/helpers/url_helper.rb:184:in `link_to'
  app/views/home/_header.html.haml:3:in `_app_views_home__header_html_haml__963867605498114295_70251249353320'
  actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.5) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
  haml (4.0.7) lib/haml/helpers.rb:89:in `non_haml'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
  app/views/home/index.html.haml:1:in `_app_views_home_index_html_haml___4058519414358563318_70251244189800'
  actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.5) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/thaichorseng/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:43:in `render'
  wicked_pdf (0.11.0) lib/wicked_pdf/pdf_helper.rb:23:in `render_with_wicked_pdf'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  warden (1.2.4) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.4) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.3) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  honeybadger (2.0.12) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
  honeybadger (2.0.12) lib/honeybadger/config.rb:189:in `with_request'
  honeybadger (2.0.12) lib/honeybadger/rack/error_notifier.rb:30:in `call'
  honeybadger (2.0.12) lib/honeybadger/rack/user_feedback.rb:28:in `call'
  honeybadger (2.0.12) lib/honeybadger/rack/user_informer.rb:18:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.8) lib/eventmachine.rb:193:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.5) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.5) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'
```

**Comment by Davidiusdadi** [comment]
+1

**Comment by Davidiusdadi** [comment]
Got it working by

replacing 
``` ruby
@file = (file.respond_to?(:to_path) ? file.to_path : file)
```

``` ruby
@file = (file.respond_to?(:filename) ? file.filename : file)
```
in

lib/compass/core/sass_extensions/functions/image_size.rb:19

After all it seems not to be a compass-rails issue...
